import { FieldMeta } from "@/components/ui/add-input";
import {
  Calendar,
  User,
  Phone,
  Mail,
  MapPin,
  Map,
  Heart,
  Baby,
  GraduationCap,
  Briefcase,
  Shield,
  Home,
  FileText,
} from "lucide-react";

export const i130Sections: {
  title: string;
  dependsOn?: { field: string; value: any };
  fields: FieldMeta[];
}[] = [
  {
    title: "Personal Information",
    fields: [
      {
        id: "dob",
        label: "Date of Birth",
        type: "date",
        icon: Calendar,
        required: true,
      },
      {
        id: "legal_name",
        label: "Full Legal Name",
        placeholder: "John Doe",
        type: "text",
        icon: User,
        required: true,
      },
      {
        id: "phone_number",
        label: "Phone Number",
        placeholder: "(555) 123-4567",
        type: "tel",
        icon: Phone,
        required: true,
      },
      {
        id: "email_address",
        label: "Email",
        placeholder: "johndoe@example.com",
        type: "email",
        icon: Mail,
        required: true,
      },
      {
        id: "marital_status",
        label: "Marital Status",
        type: "select",
        options: [
          { value: "single", label: "Single" },
          { value: "married", label: "Married" },
          { value: "divorced", label: "Divorced" },
          { value: "widowed", label: "Widowed" },
        ],
        required: true,
      },
      {
        id: "place_of_birth",
        label: "Place of Birth",
        placeholder: "New York, NY, USA",
        type: "text",
        icon: MapPin,
        required: false,
      },
      {
        id: "current_address",
        label: "Current Address",
        placeholder: "123 Main St, New York, NY",
        type: "text",
        icon: Map,
        required: true,
      },
      {
        id: "height",
        label: "Height (feet/inches)",
        placeholder: "5'8\"",
        type: "text",
        required: true,
      },
      {
        id: "weight",
        label: "Weight (lbs)",
        placeholder: "160",
        type: "text",
        required: true,
      },
      {
        id: "hair_color",
        label: "Hair Color",
        placeholder: "Brown",
        type: "text",
        required: true,
      },
      {
        id: "eye_color",
        label: "Eye Color",
        placeholder: "Hazel",
        type: "text",
        required: true,
      },
      {
        id: "has_lived_in_usa",
        label: "Have you ever lived in the USA?",
        type: "toggle",
        required: false,
      },
      {
        id: "address_history",
        label: "Address History",
        placeholder: "List your previous addresses",
        type: "text",
        required: false,
      },
      {
        id: "employment_history",
        label: "Employment History",
        placeholder: "List your employment history",
        type: "text",
        required: false,
      },
      {
        id: "previous_marriage",
        label: "Previous Marriage Information",
        placeholder: "Details about previous marriages if any",
        type: "text",
        required: false,
      },
    ],
  },
  {
    title: "Children Information",
    fields: [
      {
        id: "children_info",
        label: "Do you have children?",
        type: "toggle",
        required: false,
      },
      {
        id: "number_of_children",
        label: "Number of Children",
        placeholder: "1",
        type: "select",
        options: Array.from({ length: 10 }, (_, i) => ({
          value: String(i + 1),
          label: String(i + 1),
        })),
        required: true,
        dependsOn: { field: "children_info", value: true },
      },
      {
        id: "child_name",
        label: "Child Name",
        placeholder: "Emily Doe",
        type: "text",
        icon: User,
        required: true,
        dependsOn: { field: "children_info", value: true },
      },
      {
        id: "child_dob",
        label: "Child DOB",
        type: "date",
        icon: Calendar,
        required: true,
        dependsOn: { field: "children_info", value: true },
      },
      {
        id: "child_birth_place",
        label: "Child Birthplace",
        placeholder: "Chicago, IL, USA",
        type: "text",
        icon: MapPin,
        required: true,
        dependsOn: { field: "children_info", value: true },
      },
      {
        id: "child_city",
        label: "Child City",
        placeholder: "Chicago",
        type: "text",
        required: true,
        dependsOn: { field: "children_info", value: true },
      },
      {
        id: "child_country",
        label: "Child Country",
        placeholder: "USA",
        type: "text",
        required: true,
        dependsOn: { field: "children_info", value: true },
      },
    ],
  },
  {
    title: "Spouse Information",
    dependsOn: { field: "marital_status", value: "married" },
    fields: [
      {
        id: "spouse_name",
        label: "Spouse Name",
        placeholder: "Jane Doe",
        type: "text",
        icon: User,
        required: true,
        dependsOn: { field: "marital_status", value: "married" },
      },
      {
        id: "spouse_dob",
        label: "Spouse DOB",
        type: "date",
        icon: Calendar,
        required: true,
        dependsOn: { field: "marital_status", value: "married" },
      },
      {
        id: "date_of_marriage",
        label: "Date of Marriage",
        type: "date",
        icon: Calendar,
        required: true,
        dependsOn: { field: "marital_status", value: "married" },
      },
      {
        id: "spouse_birth_place",
        label: "Spouse Place of Birth",
        placeholder: "Los Angeles, CA, USA",
        type: "text",
        icon: MapPin,
        required: true,
        dependsOn: { field: "marital_status", value: "married" },
      },
      {
        id: "spouse_city",
        label: "Spouse City",
        placeholder: "Los Angeles",
        type: "text",
        required: true,
        dependsOn: { field: "marital_status", value: "married" },
      },
      {
        id: "spouse_state",
        label: "Spouse State",
        placeholder: "California",
        type: "text",
        required: true,
        dependsOn: { field: "marital_status", value: "married" },
      },
      {
        id: "spouse_country",
        label: "Spouse Country",
        placeholder: "USA",
        type: "text",
        required: true,
        dependsOn: { field: "marital_status", value: "married" },
      },
      {
        id: "spouse_address",
        label: "Spouse Address",
        placeholder: "123 Main St, New York, NY",
        type: "text",
        required: true,
        dependsOn: { field: "marital_status", value: "married" },
      },
    ],
  },
  {
    title: "Father Information",
    fields: [
      {
        id: "father_name",
        label: "Father's Name",
        placeholder: "John Doe Sr.",
        type: "text",
        required: false,
      },
      {
        id: "father_dob",
        label: "Father's DOB",
        type: "date",
        icon: Calendar,
        required: true,
      },
      {
        id: "father_place_of_birth",
        label: "Father's Place of Birth",
        placeholder: "Boston, MA, USA",
        type: "text",
        icon: MapPin,
        required: false,
      },
      {
        id: "parent_marriage_date",
        label: "Date of Marriage (Father & Mother)",
        type: "date",
        icon: Calendar,
        required: false,
      },
      {
        id: "father_address",
        label: "Father's Address",
        placeholder: "456 Oak St, Boston, MA",
        type: "text",
        required: true,
      },
      {
        id: "father_city",
        label: "Father's City",
        placeholder: "Boston",
        type: "text",
        required: false,
      },
      {
        id: "father_country",
        label: "Father's Country",
        placeholder: "USA",
        type: "text",
        required: true,
      },
    ],
  },
  {
    title: "Mother Information",
    fields: [
      {
        id: "mother_name",
        label: "Mother's Name",
        placeholder: "Jane Doe Sr.",
        type: "text",
        required: false,
      },
      {
        id: "mother_dob",
        label: "Mother's DOB",
        type: "date",
        icon: Calendar,
        required: true,
      },
      {
        id: "mother_place_of_birth",
        label: "Mother's Place of Birth",
        placeholder: "Chicago, IL, USA",
        type: "text",
        icon: MapPin,
        required: false,
      },
      {
        id: "mother_address",
        label: "Mother's Address",
        placeholder: "456 Oak St, Chicago, IL",
        type: "text",
        required: true,
      },
      {
        id: "mother_city",
        label: "Mother's City",
        placeholder: "Chicago",
        type: "text",
        required: false,
      },
      {
        id: "mother_country",
        label: "Mother's Country",
        placeholder: "USA",
        type: "text",
        required: true,
      },
    ],
  },
  {
    title: "Immigration Applications",
    fields: [
      {
        id: "immigration_application",
        label: "Have you previously filed any immigration application?",
        type: "toggle",
        required: false,
      },
      {
        id: "immigration_details",
        label: "Immigration Application Details",
        placeholder: "Details about your immigration applications",
        type: "text",
        required: false,
        dependsOn: { field: "immigration_application", value: true },
      },
      {
        id: "application_type",
        label: "Type of Application",
        placeholder: "e.g., Asylum, Green Card, Visa",
        type: "text",
        required: true,
        dependsOn: { field: "immigration_application", value: true },
      },
      {
        id: "application_result",
        label: "Result of Application",
        placeholder: "Approved, Denied, Pending",
        type: "text",
        required: true,
        dependsOn: { field: "immigration_application", value: true },
      },
      {
        id: "application_date",
        label: "Date of Application",
        type: "date",
        icon: Calendar,
        required: true,
        dependsOn: { field: "immigration_application", value: true },
      },
    ],
  },
  {
    title: "Legal History",
    fields: [
      {
        id: "arrest_history",
        label: "Have you been arrested before?",
        type: "toggle",
        required: false,
      },
      {
        id: "arrest_reason",
        label: "Reason for Arrest",
        placeholder: "Describe the reason",
        type: "text",
        required: true,
        dependsOn: { field: "arrest_history", value: true },
      },
      {
        id: "arrest_date",
        label: "Date of Arrest",
        type: "date",
        icon: Calendar,
        required: true,
        dependsOn: { field: "arrest_history", value: true },
      },
      {
        id: "arrest_location",
        label: "Location of Arrest",
        placeholder: "City, State, Country",
        type: "text",
        required: true,
        dependsOn: { field: "arrest_history", value: true },
      },
      {
        id: "arrest_outcome",
        label: "Outcome",
        placeholder: "e.g., Charges Dropped, Convicted, Released",
        type: "text",
        required: true,
        dependsOn: { field: "arrest_history", value: true },
      },
    ],
  },
  {
    title: "Work Authorization",
    fields: [
      {
        id: "work_permit",
        label: "Have you had a work permit in the USA?",
        type: "toggle",
        required: false,
      },
      {
        id: "work_permit_type",
        label: "Type of Work Permit",
        placeholder: "e.g., H1B, OPT, EAD",
        type: "text",
        required: true,
        dependsOn: { field: "work_permit", value: true },
      },
      {
        id: "work_permit_issue_date",
        label: "Date Issued",
        type: "date",
        icon: Calendar,
        required: true,
        dependsOn: { field: "work_permit", value: true },
      },
      {
        id: "work_permit_expiry_date",
        label: "Expiration Date",
        type: "date",
        icon: Calendar,
        required: true,
        dependsOn: { field: "work_permit", value: true },
      },
      {
        id: "illegal_work_usa",
        label: "Have you ever worked illegally in the USA?",
        type: "toggle",
        required: true,
        dependsOn: { field: "work_permit", value: true },
      },
    ],
  },
];

export const i601Sections: {
  title: string;
  dependsOn?: { field: string; value: any };
  fields: FieldMeta[];
}[] = [
  {
    title: "Personal Information",
    fields: [
      {
        id: "full_name",
        label: "Full Legal Name",
        placeholder: "John Doe",
        type: "text",
        icon: User,
        required: true,
      },
      {
        id: "phone_number",
        label: "Phone Number",
        placeholder: "(555) 123-4567",
        type: "tel",
        icon: Phone,
        required: true,
      },
      {
        id: "current_address",
        label: "Current Address",
        placeholder: "123 Main St, New York, NY",
        type: "text",
        icon: Map,
        required: true,
      },
      {
        id: "email_address",
        label: "Email Address",
        placeholder: "johndoe@example.com",
        type: "email",
        icon: Mail,
        required: true,
      },
      {
        id: "date_of_birth",
        label: "Date of Birth",
        type: "date",
        icon: Calendar,
        required: true,
      },
      {
        id: "age",
        label: "Age",
        placeholder: "25",
        type: "number",
        required: true,
      },
      {
        id: "place_of_birth",
        label: "Place of Birth",
        placeholder: "New York, NY, USA",
        type: "text",
        icon: MapPin,
        required: true,
      },
      {
        id: "height",
        label: "Height (feet/inches)",
        placeholder: "5'8\"",
        type: "text",
        required: true,
      },
      {
        id: "weight",
        label: "Weight (lbs)",
        placeholder: "160",
        type: "text",
        required: true,
      },
      {
        id: "hair_color",
        label: "Hair Color",
        placeholder: "Brown",
        type: "text",
        required: true,
      },
      {
        id: "eye_color",
        label: "Eye Color",
        placeholder: "Hazel",
        type: "text",
        required: true,
      },
    ],
  },
  {
    title: "Medical Information",
    fields: [
      {
        id: "medical_conditions",
        label: "Medical Conditions",
        placeholder: "Describe any medical conditions",
        type: "textarea",
        icon: Heart,
        required: false,
      },
      {
        id: "current_medications",
        label: "Current Medications",
        placeholder: "List current medications",
        type: "textarea",
        icon: Heart,
        required: false,
      },
      {
        id: "pregnancy_status",
        label: "Are you currently pregnant?",
        type: "toggle",
        required: false,
      },
      {
        id: "due_date",
        label: "Due Date",
        type: "date",
        icon: Calendar,
        required: true,
        dependsOn: { field: "pregnancy_status", value: true },
      },
      {
        id: "pregnancy_progress",
        label: "Pregnancy Progress",
        placeholder: "Describe pregnancy progress",
        type: "textarea",
        required: false,
        dependsOn: { field: "pregnancy_status", value: true },
      },
      {
        id: "has_health_insurance",
        label: "Do you have health insurance?",
        type: "toggle",
        required: false,
      },
      {
        id: "insured_family_members",
        label: "Insured Family Members",
        placeholder: "List insured family members",
        type: "textarea",
        required: false,
        dependsOn: { field: "has_health_insurance", value: true },
      },
    ],
  },
  {
    title: "Family Information",
    fields: [
      {
        id: "mother_us_status",
        label: "Mother's US Status",
        type: "select",
        options: [
          { value: "citizen", label: "US Citizen" },
          { value: "permanent_resident", label: "Permanent Resident" },
          { value: "visa_holder", label: "Visa Holder" },
          { value: "undocumented", label: "Undocumented" },
          { value: "unknown", label: "Unknown" },
        ],
        required: true,
      },
      {
        id: "father_us_status",
        label: "Father's US Status",
        type: "select",
        options: [
          { value: "citizen", label: "US Citizen" },
          { value: "permanent_resident", label: "Permanent Resident" },
          { value: "visa_holder", label: "Visa Holder" },
          { value: "undocumented", label: "Undocumented" },
          { value: "unknown", label: "Unknown" },
        ],
        required: true,
      },
      {
        id: "parents_in_us",
        label: "Are your parents in the US?",
        type: "toggle",
        required: false,
      },
      {
        id: "parent_medical_conditions",
        label: "Parent Medical Conditions",
        placeholder: "Describe parent medical conditions",
        type: "textarea",
        required: false,
      },
      {
        id: "sibling_names",
        label: "Sibling Names",
        placeholder: "List sibling names",
        type: "textarea",
        required: false,
      },
      {
        id: "sibling_legal_statuses",
        label: "Sibling Legal Statuses",
        placeholder: "Describe sibling legal statuses",
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    title: "Children Information",
    fields: [
      {
        id: "has_children",
        label: "Do you have children?",
        type: "toggle",
        required: false,
      },
      {
        id: "number_of_children",
        label: "Number of Children",
        placeholder: "1",
        type: "select",
        options: Array.from({ length: 10 }, (_, i) => ({
          value: String(i + 1),
          label: String(i + 1),
        })),
        required: true,
        dependsOn: { field: "has_children", value: true },
      },
      {
        id: "children_live_with_user",
        label: "Do your children live with you?",
        type: "toggle",
        required: false,
        dependsOn: { field: "has_children", value: true },
      },
      {
        id: "children_names",
        label: "Children Names",
        placeholder: "List children names",
        type: "textarea",
        required: true,
        dependsOn: { field: "has_children", value: true },
      },
      {
        id: "children_legal_status",
        label: "Children Legal Status",
        placeholder: "Describe children legal status",
        type: "textarea",
        required: true,
        dependsOn: { field: "has_children", value: true },
      },
      {
        id: "children_ages",
        label: "Children Ages",
        placeholder: "List children ages",
        type: "textarea",
        required: true,
        dependsOn: { field: "has_children", value: true },
      },
      {
        id: "children_guardian",
        label: "Children Guardian",
        placeholder: "Who is the guardian of your children?",
        type: "text",
        required: false,
        dependsOn: { field: "has_children", value: true },
      },
      {
        id: "children_guardian_reason",
        label: "Guardian Reason",
        placeholder: "Why is this person the guardian?",
        type: "textarea",
        required: false,
        dependsOn: { field: "has_children", value: true },
      },
      {
        id: "court_ordered_custody",
        label: "Court Ordered Custody",
        placeholder: "Describe court ordered custody arrangements",
        type: "textarea",
        required: false,
        dependsOn: { field: "has_children", value: true },
      },
      {
        id: "children_special_services_status",
        label: "Do your children receive special services?",
        type: "toggle",
        required: false,
        dependsOn: { field: "has_children", value: true },
      },
      {
        id: "children_special_services",
        label: "Children Special Services",
        placeholder: "Describe special services",
        type: "textarea",
        required: false,
        dependsOn: { field: "children_special_services_status", value: true },
      },
    ],
  },
  {
    title: "Education Information",
    fields: [
      {
        id: "highest_education_level",
        label: "Highest Education Level",
        type: "select",
        options: [
          { value: "elementary", label: "Elementary" },
          { value: "high_school", label: "High School" },
          { value: "some_college", label: "Some College" },
          { value: "associates", label: "Associate's Degree" },
          { value: "bachelors", label: "Bachelor's Degree" },
          { value: "masters", label: "Master's Degree" },
          { value: "doctorate", label: "Doctorate" },
        ],
        required: true,
      },
      {
        id: "education_location",
        label: "Education Location",
        placeholder: "Where did you receive your education?",
        type: "text",
        icon: MapPin,
        required: true,
      },
      {
        id: "has_degrees_or_certifications",
        label: "Do you have degrees or certifications?",
        type: "toggle",
        required: false,
      },
      {
        id: "degrees_or_certifications",
        label: "Degrees or Certifications",
        placeholder: "List your degrees and certifications",
        type: "textarea",
        required: false,
        dependsOn: { field: "has_degrees_or_certifications", value: true },
      },
    ],
  },
  {
    title: "Legal History",
    fields: [
      {
        id: "has_committed_crime",
        label: "Have you committed any crime?",
        type: "toggle",
        required: false,
      },
      {
        id: "victim_of_crime_status",
        label: "Have you ever been a victim of crime?",
        type: "toggle",
        required: false,
      },
      {
        id: "crime_type",
        label: "Type of Crime",
        placeholder: "Describe the type of crime",
        type: "textarea",
        required: false,
        dependsOn: { field: "victim_of_crime_status", value: true },
      },
      {
        id: "who_is_victim",
        label: "Who is the victim?",
        placeholder: "Describe who the victim is",
        type: "textarea",
        required: false,
        dependsOn: { field: "victim_of_crime_status", value: true },
      },
    ],
  },
  {
    title: "US Immigration History",
    fields: [
      {
        id: "has_lived_in_us",
        label: "Have you ever lived in the US?",
        type: "toggle",
        required: false,
      },
      {
        id: "us_entry_dates",
        label: "US Entry Dates",
        placeholder: "List your US entry dates",
        type: "textarea",
        required: false,
        dependsOn: { field: "has_lived_in_us", value: true },
      },
      {
        id: "us_exit_dates",
        label: "US Exit Dates",
        placeholder: "List your US exit dates",
        type: "textarea",
        required: false,
        dependsOn: { field: "has_lived_in_us", value: true },
      },
      {
        id: "us_entry_visa_status",
        label: "US Entry Visa Status",
        placeholder: "Describe your US entry visa status",
        type: "textarea",
        required: false,
        dependsOn: { field: "has_lived_in_us", value: true },
      },
      {
        id: "was_deported",
        label: "Were you ever deported?",
        type: "toggle",
        required: false,
      },
      {
        id: "deportation_date",
        label: "Deportation Date",
        type: "date",
        icon: Calendar,
        required: false,
        dependsOn: { field: "was_deported", value: true },
      },
      {
        id: "deportation_city",
        label: "Deportation City",
        placeholder: "City where deportation occurred",
        type: "text",
        required: false,
        dependsOn: { field: "was_deported", value: true },
      },
      {
        id: "has_submitted_waiver_application",
        label: "Have you submitted a waiver application?",
        type: "toggle",
        required: false,
      },
      {
        id: "has_appeared_in_immigration_court",
        label: "Have you appeared in immigration court?",
        type: "toggle",
        required: false,
      },
    ],
  },
  {
    title: "Marital Status",
    fields: [
      {
        id: "has_been_married_before",
        label: "Have you been married before?",
        type: "toggle",
        required: false,
      },
      {
        id: "is_married",
        label: "Are you currently married?",
        type: "toggle",
        required: false,
      },
      {
        id: "spouse_legal_status",
        label: "Spouse Legal Status",
        type: "select",
        options: [
          { value: "citizen", label: "US Citizen" },
          { value: "permanent_resident", label: "Permanent Resident" },
          { value: "visa_holder", label: "Visa Holder" },
          { value: "undocumented", label: "Undocumented" },
          { value: "unknown", label: "Unknown" },
        ],
        required: false,
        dependsOn: { field: "is_married", value: true },
      },
    ],
  },
];

export const caseTypeDefinitions = {
  I130: {
    sections: i130Sections,
    name: "I-130 Petition for Alien Relative",
    description:
      "Petition for a family member to immigrate to the United States",
  },
  I485: {
    sections: i130Sections,
    name: "I-485 Application to Register Permanent Residence",
    description: "Application to adjust status to permanent resident",
  },
  I601: {
    sections: i601Sections,
    name: "I-601 Application for Waiver of Grounds of Inadmissibility",
    description: "Application for waiver of certain grounds of inadmissibility",
  },
};

export const caseTypeFieldMappings: Record<
  string,
  Record<string, Record<string, string>>
> = {
  I130: {
    passport: {
      name: "legal_name",
      passport_number: "passportNumber",
      country_of_issue: "passportIssuingCountry",
      date_of_birth: "todayDate",
      place_of_birth: "place_of_birth",
      gender: "gender",
      issue_date: "passportIssueDate",
      expiration_date: "passportExpiryDate",
      nationality: "nationality",
    },
    birth_certificate: {
      full_name: "legal_name",
      date_of_birth: "todayDate",
      place_of_birth: "place_of_birth",
      father_name: "father_name",
      mother_name: "mother_name",
      certificate_number: "birthCertificateNumber",
      issuing_authority: "birthIssuingAuthority",
    },
    marriage_certificate: {
      spouse_1_name: "spouse_name",
      spouse_2_name: "spouseAltName",
      marriage_date: "date_of_marriage",
      marriage_location: "spouse_address",
      certificate_number: "marriageCertificateNumber",
      officiant_name: "officiantName",
      issuing_authority: "marriageIssuingAuthority",
    },
    divorce_decree: {
      party_1_name: "spouse_name",
      party_2_name: "spouseAltName",
      divorce_date: "divorceDate",
      court_name: "courtName",
      case_number: "divorceCaseNumber",
    },
    green_card: {
      name: "legal_name",
      uscis_a_number: "uscisNumber",
      card_number: "greenCardNumber",
      date_of_birth: "todayDate",
      issue_date: "greenCardIssueDate",
      expiration_date: "greenCardExpiryDate",
    },
    drivers_license: {
      name: "legal_name",
      license_number: "licenseNumber",
      date_of_birth: "todayDate",
      address: "current_address",
      issue_date: "licenseIssueDate",
      expiration_date: "licenseExpiryDate",
      state: "licenseIssuingState",
    },
    social_security_card: {
      name: "legal_name",
      social_security_number: "socialSecurityNumber",
    },
    tax_return: {
      name: "legal_name",
      ssn: "socialSecurityNumber",
      tax_year: "taxYear",
      income_amount: "incomeAmount",
      filing_status: "filingStatus",
      employer_name: "employerName",
    },
    medical_exam: {
      name: "legal_name",
      date_of_birth: "todayDate",
      exam_date: "medicalExamDate",
      civil_surgeon_name: "civilSurgeonName",
      vaccination_status: "vaccinationStatus",
    },
    police_clearance: {
      name: "legal_name",
      date_of_birth: "todayDate",
      country_or_jurisdiction: "clearanceCountry",
      certificate_number: "clearanceCertificateNumber",
      issue_date: "clearanceIssueDate",
      criminal_record_status: "criminalRecordStatus",
    },
  },
  I601: {
    passport: {
      name: "full_name",
      passport_number: "passportNumber",
      country_of_issue: "passportIssuingCountry",
      date_of_birth: "date_of_birth",
      place_of_birth: "place_of_birth",
      gender: "gender",
      issue_date: "passportIssueDate",
      expiration_date: "passportExpiryDate",
      nationality: "nationality",
    },
    birth_certificate: {
      full_name: "full_name",
      date_of_birth: "date_of_birth",
      place_of_birth: "place_of_birth",
      father_name: "father_name",
      mother_name: "mother_name",
      certificate_number: "birthCertificateNumber",
      issuing_authority: "birthIssuingAuthority",
    },
    medical_exam: {
      name: "full_name",
      date_of_birth: "date_of_birth",
      exam_date: "medicalExamDate",
      civil_surgeon_name: "civilSurgeonName",
      vaccination_status: "vaccinationStatus",
      medical_conditions: "medical_conditions",
      current_medications: "current_medications",
    },
    police_clearance: {
      name: "full_name",
      date_of_birth: "date_of_birth",
      country_or_jurisdiction: "clearanceCountry",
      certificate_number: "clearanceCertificateNumber",
      issue_date: "clearanceIssueDate",
      criminal_record_status: "criminalRecordStatus",
    },
  },
};

export const caseTypeVoiceBotMappings: Record<
  string,
  Record<string, string>
> = {
  I130: {
    full_legal_name: "legal_name",
    height: "height",
    weight: "weight",
    eye_color: "eye_color",
    hair_color: "hair_color",
    phone_number: "phone_number",
    email_address: "email_address",
    marital_status: "marital_status",
    current_address: "current_address",
    children_info: "children_info",
    number_of_children: "number_of_children",
    father_dob: "father_dob",
    father_residence: "father_address",
    father_country_birth: "father_country",
    mother_dob: "mother_dob",
    mother_residence: "mother_address",
    mother_country_birth: "mother_country",
    immigration_application: "immigration_application",
    arrest_history: "arrest_history",
    has_lived_in_usa: "has_lived_in_usa",
    address_history: "address_history",
    previous_marriage: "previous_marriage",
    employment_history: "employment_history",
  },
  I601: {
    full_name: "full_name",
    phone_number: "phone_number",
    current_address: "current_address",
    email_address: "email_address",
    date_of_birth: "date_of_birth",
    age: "age",
    place_of_birth: "place_of_birth",
    medical_conditions: "medical_conditions",
    current_medications: "current_medications",
    pregnancy_status: "pregnancy_status",
    due_date: "due_date",
    pregnancy_progress: "pregnancy_progress",
    mother_us_status: "mother_us_status",
    father_us_status: "father_us_status",
    has_children: "has_children",
    number_of_children: "number_of_children",
    children_live_with_user: "children_live_with_user",
    children_names: "children_names",
    children_legal_status: "children_legal_status",
    children_ages: "children_ages",
    children_guardian: "children_guardian",
    children_guardian_reason: "children_guardian_reason",
    court_ordered_custody: "court_ordered_custody",
    children_special_services_status: "children_special_services_status",
    children_special_services: "children_special_services",
    highest_education_level: "highest_education_level",
    education_location: "education_location",
    has_degrees_or_certifications: "has_degrees_or_certifications",
    degrees_or_certifications: "degrees_or_certifications",
    is_us_business_owner: "is_us_business_owner",
    victim_of_crime_status: "victim_of_crime_status",
    crime_type: "crime_type",
    who_is_victim: "who_is_victim",
    has_lived_in_us: "has_lived_in_us",
    us_entry_dates: "us_entry_dates",
    us_exit_dates: "us_exit_dates",
    us_entry_visa_status: "us_entry_visa_status",
    was_deported: "was_deported",
    deportation_date: "deportation_date",
    deportation_city: "deportation_city",
    has_submitted_waiver_application: "has_submitted_waiver_application",
    has_appeared_in_immigration_court: "has_appeared_in_immigration_court",
    hair_color: "hair_color",
    eye_color: "eye_color",
    height: "height",
    weight: "weight",
    has_been_married_before: "has_been_married_before",
    is_married: "is_married",
    spouse_legal_status: "spouse_legal_status",
    has_committed_crime: "has_committed_crime",
    has_health_insurance: "has_health_insurance",
    insured_family_members: "insured_family_members",
    job_offers_benefits: "job_offers_benefits",
    receives_benefits: "receives_benefits",
    benefits_list: "benefits_list",
    sibling_names: "sibling_names",
    sibling_legal_statuses: "sibling_legal_statuses",
    parents_in_us: "parents_in_us",
    parent_medical_conditions: "parent_medical_conditions",
    additional_information: "additional_information",
    user_feedback: "user_feedback",
  },
};
